import Head from "next/head";
import {
  Button,
  ButtonGroup,
  Container,
  Heading,
  VStack,
} from "@chakra-ui/react";
import { Form, Formik } from "formik";
import * as Yup from "yup";
import { LoginInput } from "@/modules/components/login/LoginInput";
import { useRouter } from "next/router";

const Register = () => {
  const router = useRouter();
  return (
    <Container h={"100vh"}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Formik
        initialValues={{
          username: "",
          email: "",
          password: "",
          confirm: "",
        }}
        validationSchema={Yup.object({
          username: Yup.string()
            .required("Username is required")
            .min(6, "Username is too short"),
          password: Yup.string()
            .required("Password is required")
            .min(6, "Password is too short"),
          confirm: Yup.string()
            .required("Password confirmation is required")
            .oneOf([Yup.ref("password")], "Passwords do not match"),
          email: Yup.string()
            .required("Email is required")
            .email("Invalid email"),
        })}
        onSubmit={(values, actions) => {
          console.log(values);
          actions.resetForm();
        }}
      >
        <VStack h={"100%"} justify={"center"}>
          <VStack as={Form} shadow={"2xl"} w={"100%"} bg={"gray.50"} p={"4"}>
            <Heading>Register</Heading>
            <LoginInput name="email" label="Email" />
            <LoginInput name="username" label="Username" />
            <LoginInput name="password" label="Password" type="password" />
            <LoginInput
              name="confirm"
              label="Confirm Password"
              type="password"
            />
            <ButtonGroup colorScheme="purple" w={"100%"} size={"lg"} pt={"4"}>
              <Button
                variant={"outline"}
                w={"100%"}
                onClick={() => router.push("/login")}
              >
                Login
              </Button>
              <Button w={"100%"} type="submit">
                Sign Up
              </Button>
            </ButtonGroup>
          </VStack>
        </VStack>
      </Formik>
    </Container>
  );
};

export default Register;
